---

- block:
  - name: create tinc directory structure
    file:
      path: /etc/tinc/{{ec2_tag_tinc_netname}}/hosts
      state: directory

  - name: create tinc.conf from template
    template:
      src: tinc.conf.j2
      dest: /etc/tinc/{{ec2_tag_tinc_netname}}/tinc.conf